global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"
  - "recording-rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sample-apps'
    static_configs:
      - targets: ['apps:3000']
    metrics_path: '/metrics'

  - job_name: 'pipeline-exporter'
    static_configs:
      - targets: ['pipeline-exporter:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']